//
//  ClubViewModel.swift
//  ClubsCollectionView
//
//  Created by tobi adegoroye on 25/05/2021.
//

import UIKit

class LeagueViewModel {
    
    private(set) var leagues: [League] = [
        League(name: "Premier-League", image: Image.premierLeague, colour: UIColor(named: "red"), teams: [
            Team(id: .arsenal,name: "Arsenal",manager: .init(name: "Mikel Arteta", job: .manager, managerID: .Arteta), info: "Arsenal Football Club is a professional football club based in Islington, London, England, that plays in the Premier League, the top flight of English football. The club has won 13 league titles (including one unbeaten title), a record 14 FA Cups, two League Cups, 16 FA Community Shields, the League Centenary Trophy, one European Cup Winners' Cup, and one Inter-Cities Fairs Cup.",founded: "October 1886"),
            
            Team(id: .astonVilla,name: "Aston Villa", manager: .init(name: "Dean Smith", job: .headCoach, managerID: .Dean), info: "Aston Villa Football Club is an English professional football club based in Aston, Birmingham. The club competes in the Premier League, the top tier of the English football league system. Founded in 1874, they have played at their home ground, Villa Park, since 1897. Aston Villa were one of the founder members of the Football League in 1888 and of the Premier League in 1992. Villa are one of only five English clubs to have won the European Cup, in 1981–82. They have also won the Football League First Division seven times, the FA Cup seven times, the League Cup five times, and the European (UEFA) Super Cup once.",founded: "November 1874"),
            Team(id: .brighton, name: "Brighton", manager: .init(name: "Graham Potter", job: .headCoach, managerID: .Graham), info: "Brighton & Hove Albion Football Club, commonly referred to simply as Brighton, is an English professional football club based in the city of Brighton and Hove. They compete in the Premier League, the top tier of the English football league system. The club's home ground is the 30,750-capacity Falmer Stadium, situated in Falmer to the north east of the city.",founded: "June 1901"),
            
            Team(id: .burnley,name: "Burnley",manager: .init(name: "Sean Dyche", job: .manager, managerID: .Sean), info: "Burnley Football Club is an English association football club based in Burnley, Lancashire. Founded on 18 May 1882, it was one of the first to become professional (in 1883), and subsequently put pressure on the Football Association to permit payments to players. The club entered the FA Cup for the first time in 1885–86 and was one of the 12 founder members of the Football League in 1888–89. The team currently competes in the Premier League, the top tier of English football.",founded: "May 1882"),
            
            Team(id: .chelsea, name: "Chelsea",manager: .init(name: "Frank Lampard", job: .headCoach, managerID: .Thomas), info: "Chelsea Football Club are an English professional football club based in Fulham, London. Founded in 1905, the club competes in the Premier League, the top division of English football. Chelsea are among England's most successful clubs, having won over thirty competitive honours, including six league titles and six European trophies. Their home ground is Stamford Bridge.",founded: "March 1905"),
            
            Team(id: .everton,name: "Everton", manager: .init(name: "Carlo Ancelotti", job: .manager, managerID: .Ancelotti), info: "Everton Football Club is an English professional football club based in Liverpool that competes in the Premier League, the top tier of English football. The club has competed in the top division for a record 117 seasons, missing only four top-flight seasons (1930–31, 1951–52, 1952–53, 1953–54) since the creation of the Football League, of which it was a founding member. Everton are the second-longest continuous serving club in English top flight football and has won nine league titles, five FA Cups, one European Cup Winners' Cup and nine Charity Shields.",founded: "1878"),
            
            Team(id: .fulham,name: "Fulham", manager: .init(name: "Scott Parker", job: .headCoach, managerID: .Scott), info: "Fulham Football Club is an English professional association football club based in Fulham, London. They currently compete in the Premier League, the highest level of the English football league system. Founded in 1879, they are London's oldest football club playing professionally.",founded: "1879"),
            
            Team(id: .leeds, name: "Leeds",manager: .init(name: "Marcelo Bielsa", job: .headCoach, managerID: .Marcelo), info: "Leeds United Football Club is an English professional football club based in the city of Leeds, West Yorkshire. The club was formed in 1919 following the disbanding of Leeds City by the Football League and took over their Elland Road stadium. The club currently competes in the Premier League, the top flight of English football, following promotion from the EFL Championship during the 2019—20 season. Most of their history has been spent competing in the first tier of English football. Their longest continuous spell inside the first tier was a period of 18 years between 1964 and 1982, while their longest period outside of it spanned 16 years between 2004 and 2020.",
                 founded: "October 1919"),
            
            Team(id: .leicester, name: "Leicester",manager: .init(name: "Brendan Rodgers", job: .manager, managerID: .Brendan), info: "Leicester City Football Club is an English professional football club based in Leicester in the East Midlands. The club competes in the Premier League, the top division of England's football league system, and plays its home matches at the King Power Stadium.", founded: "1884"),
            Team(id: .liverpool,name: "Liverpool", manager: .init(name: "Jürgen Klopp", job: .manager, managerID: .Jurgen), info: "Liverpool Football Club is a professional football club in Liverpool, England, that competes in the Premier League, the top tier of English football. Domestically, the club has won nineteen League titles, seven FA Cups, a record eight League Cups and fifteen FA Community Shields. In international competitions, the club has won six European Cups, more than any other English club, three UEFA Cups, four UEFA Super Cups (also English records) and one FIFA Club World Cup.",founded: "June 1892"),
            Team(id: .manchesterCity,name: "Manchester City", manager: .init(name: "Pep Guardiola", job: .manager, managerID: .Pep), info: "Manchester City Football Club is an English football club based in Manchester that competes in the Premier League, the top flight of English football. Founded in 1880 as St. Mark's (West Gorton), it became Ardwick Association Football Club in 1887 and Manchester City in 1894. The club's home ground is the City of Manchester Stadium in east Manchester, to which it moved in 2003, having played at Maine Road since 1923. The club adopted their sky blue home shirts in 1894 in the first season of the club's current iteration, that have been used ever since.",founded: "1880"),
            Team(id: .manchesterUnited, name: "Manchester United",manager: .init(name: "Ole Gunnar Solskjær", job: .manager, managerID: .Ole), info: "Manchester United Football Club is a professional football club based in Old Trafford, Greater Manchester, England, that competes in the Premier League, the top flight of English football. Nicknamed \"the Red Devils\", the club was founded as Newton Heath LYR Football Club in 1878, changed its name to Manchester United in 1902 and moved to its current stadium, Old Trafford, in 1910.",founded: "1902"),
            Team(id: .newcastle,name: "Newcastle United", manager: .init(name: "Steve Bruce", job: .manager, managerID: .Steve), info: "Newcastle United Football Club is an English professional football club based in Newcastle upon Tyne, Tyne and Wear, that plays in the Premier League, the top flight of English football. Founded in 1892 by the merger of Newcastle East End and Newcastle West End. The team plays its home matches at St. James' Park. Per the Taylor Report's requirement that all Premier League clubs have an all-seater stadium, the ground was adjusted in the mid-1990s and now has a capacity of 52,305.",founded: "December 1892"),
            Team(id: .palace,name: "Crystal Palace",manager: .init(name: "Roy Hodgson", job: .manager, managerID: .Roy), info: "Crystal Palace Football Club is a professional football club based in Selhurst, South London, England, who currently compete in the Premier League, the highest level of English football. Although their official founding date is 1905, the club claim to be a continuation of the original amateur Crystal Palace football club first established in 1861, which would make them the oldest professional football club in the world, after historians discovered a direct lineage through their ownership under the same Crystal Palace Company. Both the amateur and professional clubs played inside the grounds of the Crystal Palace Exhibition building, with the professional club playing at the FA Cup Final stadium until 1915, when they were forced to leave due to the outbreak of the First World War. In 1924, they moved to their current home at Selhurst Park.",founded: "September 1905"),
            Team(id: .sheffield,name: "Sheffield United",manager: .init(name: "Chris Wilder", job: .manager, managerID: .Chris), info: "Sheffield United Football Club is a professional football club in Sheffield, South Yorkshire, England, which competes in the Premier League, the top division of English football. They formed in 1889, as an offshoot of Sheffield United Cricket Club, and are nicknamed The Blades due to Sheffield's history of steel production. They have played home games at Bramall Lane since their formation.",founded: "March 1889"),
            Team(id: .southampton, name: "Southampton",manager: .init(name: "Ralph Hasenhüttl", job: .manager, managerID: .Ralph), info: "Southampton Football Club is an English professional football club based in Southampton, Hampshire, which plays in the Premier League, the top tier of English football.", founded: "November 1885"),
            Team(id: .tottenham, name: "Tottenham Hotspurs",manager: .init(name: "José Mourinho", job: .manager, managerID: .Ryan), info: "Founded in 1882, Tottenham won the FA Cup for the first time in 1901, the only non-League club to do so since the formation of the Football League in 1888. Tottenham were the first club in the 20th century to achieve the League and FA Cup Double, winning both competitions in the 1960–61 season.",founded: "September 1882"),
            Team(id: .westBrom,name: "West Brom",manager: .init(name: "Slaven Bilić", job: .manager, managerID: .Sam), info: "West Bromwich Albion Football Club (/ˈbrɒmɪdʒ, -ɪtʃ/) is an English professional football club based in West Bromwich, West Midlands, England, that competes in the Premier League, the top tier of English football. The club was formed in 1878 and has played at its home ground, The Hawthorns, since 1900.",founded: "1878"),
            
            Team(id: .wolves,name: "Wolves",manager: .init(name: "Nuno Espírito Santo", job: .headCoach, managerID: .Nuno), info: "Wolverhampton Wanderers Football Club, commonly known as Wolves, is a professional association football club based in the city of Wolverhampton in the West Midlands, England. Formed as St. Luke's F.C. in 1877, the club has played at Molineux Stadium since 1889 and has been competing in the Premier League, the top division of English football, since winning promotion in 2018. The 2020–21 season is the club's 66th season in total at the highest level.",founded: "1877"),
            
        ]),
        
        League(name: "LaLiga", image: Image.laLiga, colour: UIColor(named: "red"), teams: [
            
            Team(id: .Alavés, name: "Alavés", manager: .init(name: "Javier Calleja", job: .headCoach, managerID: .JavierCalleja), info: "Deportivo Alavés, S.A.D. (Spanish pronunciation: [depoɾˈtiβo alaˈβes]; Sporting Alavés), usually abbreviated to Alavés, is a Spanish football club based in Vitoria-Gasteiz, Álava, in the autonomous community of the Basque Country. Founded on 1 July 1920 as Sport Friends Club, it has played in the highest football category of The Liga Nacional de Fútbol Profesional, La Liga, since the 2016–17 season.It is recognized as the third most successful team in the Basque Country following Athletic Club of Bilbao and Real Sociedad de Futbol of San Sebastián. Its biggest success was in 2001 when, in the year of its debut in European competition, it reached the final of the 2001 UEFA Cup Final, where it played against Liverpool. It was defeated 5–4 by golden goal. In 2017, the club reached the final of the Copa del Rey, losing out 3–1 to Barcelona.",founded: ""),
            
            Team(id: .AthleticBilbao, name: "AthleticBilbao", manager: .init(name: "Marcelino", job: .headCoach, managerID: .Marcelino), info: "Athletic Club (Basque: Bilboko Athletic Kluba; Spanish: Athletic Club de Bilbao), commonly known as Athletic Bilbao or just Athletic, is a professional football club based in the city of Bilbao in the Basque Country in Spain. They are known as Los Leones (The Lions) because their stadium was built near a church called San Mamés (Saint Mammes). Mammes was an early Christian thrown to the lions by the Romans. Mammes pacified the lions and was later made a saint. The team plays its home matches at the San Mamés Stadium. Its home colours are red and white-striped shirts with black shorts.Athletic are the fourth most successful club in La Liga with eight titles to their name. In the table of Copa del Rey titles, Athletic is second only to Barcelona, having won it 23 times.[note 1] It is also the most successful Basque football club in both league and cup titles won. The club also has one of the most successful women's teams in Spain, which has won five championships in the Primera División Femenina.", founded: ""),
            
            Team(id: .AtléticoMadrid, name: "AtléticoMadrid", manager: .init(name: "Diego Simeone", job: .headCoach,  managerID: .DiegoSimeone), info: "Club Atlético de Madrid, S.A.D. (Spanish pronunciation: [ˈkluβ aˈtletiko ðe maˈðɾið]; meaning Athletic Club of Madrid), commonly referred to as Atlético Madrid in English or simply as Atlético or Atleti, is a Spanish professional football club based in Madrid, that play in La Liga. The club play their home games at the Wanda Metropolitano Stadium, which has a capacity of 68,456.[3]", founded: ""),
            
            Team(id: .Barcelona, name: "Barcelona", manager: .init(name: "Ronald Koeman", job: .headCoach, managerID: .RonaldKoeman), info: "Founded in 1899 by a group of Swiss, Spanish, English, and Catalan footballers led by Joan Gamper, the club has become a symbol of Catalan culture and Catalanism, hence the motto Més que un club (More than a club). Unlike many other football clubs, the supporters own and operate Barcelona. It is the fourth-most valuable sports team in the world, worth $4.06 billion, and the world's richest football club in terms of revenue, with an annual turnover of €840.8 million.[2][3] The official Barcelona anthem is the Cant del Barça, written by Jaume Picas and Josep Maria Espinàs.[4] Barcelona traditionally play in dark shades of blue and red stripes, leading to the nickname Blaugrana.", founded: ""),
        ]),
        
        League(name: "Ligue1", image: Image.ligue1, colour: UIColor(named: "red"), teams: [
            Team(id: .PSG,name: "PSG",manager: .init(name: "Mauricio Poch", job: .manager, managerID: .Mauricio), info: "Paris Saint-Germain Football Club (French pronunciation: ​[paʁi sɛ̃ ʒɛʁmɛ̃]), commonly referred to as Paris Saint-Germain, Paris SG, or simply Paris or PSG, is a professional football club based in Paris, France. They compete in Ligue 1, the top division of French football. PSG are France's most successful club, having won more than 40 official honours, including nine league titles and one major European trophy. Their home ground is the Parc des Princes. Founded in 1970, the Parisians won their first major honour, the French Cup, in 1982 and their first Ligue 1 title in 1986. The 1990s was among the most successful periods in PSG's history; they claimed a second league, three French Cups, two League Cups, two French Super Cups and the UEFA Cup Winners' Cup in 1996. After suffering a decline in fortunes during the 2000s, the Red and Blues have enjoyed a revival since 2011 with increased financial backing; they have clinched seven league titles and twenty national cups, achieving unparalleled dominance in domestic competitions. In 2020, the club reached the UEFA Champions League final for the first time, losing to Bayern Munich.",founded: "1970"),
            
            Team(id: .Angers, name: "Angers", manager: .init(name: "Gérald Baticle", job: .headCoach, managerID: .GéraldBaticle), info: "Angers Sporting Club de l'Ouest, commonly referred to as Angers SCO or simply Angers (French pronunciation: ​[ɑ̃ʒe]), is a French professional football club based in Angers in Pays de la Loire in western France.", founded: "1919"),
            Team(id: .Bordeaux, name: "Bordeaux", manager: .init(name: "Jean Louis Gasset", job: .headCoach, managerID: .JeanLouisGasset), info: "Football Club des Girondins de Bordeaux (French pronunciation: ​[ʒiʁɔ̃dɛ̃ də bɔʁdo]), commonly referred to as Girondins de Bordeaux (Occitan: Girondins de Bordèu) or simply Bordeaux, is a French professional football club based in the city of Bordeaux in Gironde, Nouvelle-Aquitaine. ", founded: "1881"),
            Team(id: .Brest, name: "Brest", manager: .init(name: "Olivier Dall Oglio", job: .headCoach, managerID: .OlivierDallOglio), info: "Stade Brestois 29 is a French football club based in Brest. It was founded in 1950 following the merger of five local patronages, including Armoricaine de Brest, founded in 1903.", founded: "1903"),
            Team(id: .Dijon, name: "Dijon", manager: .init(name: "David Linarès", job: .headCoach, managerID: .DavidLinarès), info: "Dijon Football Côte d'Or (French pronunciation: ​[diʒɔ̃ futbol kot dɔʁ]; literally Dijon Football Gold Coast), commonly referred to as Dijon FCO or simply as Dijon, is a French association football club based in Dijon.", founded: "1998"),
            Team(id: .Lens, name: "Lens", manager: .init(name: "Franck Haise", job: .headCoach, managerID: .FranckHaise), info: "Racing Club de Lens (French pronunciation: ​[ʁasiŋ klœb də lɑ̃s], commonly referred to as RC Lens or simply Lens) is a French football club based in the northern city of Lens in the Pas-de-Calais department.", founded: "1906"),
        ]),
        
        League(name: "Serie-A", image: Image.serieA, colour: UIColor(named: "red"), teams: [
            Team(id: .Juventus,name: "Juventus",manager: .init(name: "Allegri", job: .manager, managerID: .Allegri), info: "Juventus Football Club (from Latin: iuventūs, youth; Italian pronunciation: [juˈvɛntus]), colloquially known as Juventus and Juve (pronounced [ˈjuːve]),[3] is a professional football club based in Turin, Piedmont, Italy, that competes in the Serie A, the top flight of Italian football. Founded in 1897 by a group of Torinese students, the club has worn a black and white striped home kit since 1903 and has played home matches in different grounds around its city, the latest being the 41,507-capacity Juventus Stadium. Nicknamed Vecchia Signora (the Old Lady), the club has won 36 official league titles, 14 Coppa Italia titles and nine Supercoppa Italiana titles, being the record holder for all these competitions; two Intercontinental Cups, two European Cups / UEFA Champions Leagues, one European Cup Winners' Cup, a joint national record of three UEFA Cups, two UEFA Super Cups and a joint national record of one UEFA Intertoto Cup.[4][5] Consequently, the side leads the historical Federazione Italiana Giuoco Calcio (FIGC) classify[a] whilst on the international stage occupies the sixth position in Europe and the twelfth in the world for most confederation titles won with eleven trophies,[7] as well as the fourth in the all-time Union of European Football Associations (UEFA) competitions ranking,[b] having obtained the highest coefficient score during seven seasons since its inception in 1979, the most for an Italian team in both cases and joint second overall in the last cited.Founded with the name of Sport-Club Juventus, initially as an athletics club,[9] it is the second oldest of its kind still active in the country after Genoa's football section (1893) and has competed uninterruptedly in the top flight league (reformulated as Serie A from 1929) since its debut in 1900 after changing its name to Foot-Ball Club Juventus, with the exception of the 2006–07 season, being managed by the industrial Agnelli family almost continuously since 1923.[c] The relationship between the club and that dynasty is the oldest and longest in national sports, making Juventus one of the first professional sporting clubs ante litteram in the country,[11] having established itself as a major force in the national stage since the 1930s and at confederation level since the mid-1970s[12] and becoming one of the first ten wealthiest in world football in terms of value, revenue and profit since the mid-1990s,[13] being listed on the Borsa italiana since 2001.[14]",founded: "1970"),
            Team(id: .Atalanta,name: "Atalanta",manager: .init(name: "Gian Piero Gasperini", job: .manager, managerID: .GianPieroGasperini), info: "Atalanta was founded in 1907 by Liceo Classico Paolo Sarpi students and is nicknamed La Dea, the Nerazzurri and the Orobici. The club plays in blue-and-black vertically striped shirts, black shorts and black socks. The club plays its home matches at the 21,300 seat Gewiss Stadium. In Italy, Atalanta is sometimes called Regina delle provinciali (queen of the provincial clubs) to mark the fact that the club is the most consistent among Italian clubs not based in a regional capital, having played 60 seasons in Serie A, 28 seasons in Serie B, and only one in Serie C. Atalanta has a long-standing rivalry with nearby club Brescia.",founded: "1907"),
            Team(id: .Internazionale,name: "Atalanta",manager: .init(name: "Simone Inzaghi", job: .manager, managerID: .SimoneInzaghi), info: "Founded in 1908 following a schism within the Milan Cricket and Football Club (now A.C. Milan), Inter won its first championship in 1910. Since its formation, the club has won 31 domestic trophies, including 19 league titles, 7 Coppa Italia and 5 Supercoppa Italiana. From 2006 to 2010, the club won five successive league titles, equalling the all-time record at that time.[10] They have won the Champions League three times: two back-to-back in 1964 and 1965 and then another in 2010. Their latest win completed an unprecedented Italian seasonal treble, with Inter winning the Coppa Italia and the Scudetto the same year.[11] The club has also won three UEFA Cups, two Intercontinental Cups and one FIFA Club World Cup.",founded: "1908"),
            Team(id: .Milan,name: "Milan",manager: .init(name: "Stefano Pioli", job: .manager, managerID: .StefanoPioli), info: "A.C. Milan's 18 FIFA and UEFA trophies is the fourth highest out of any club (joint with Boca Juniors), and the most out of any Italian club.[6][7][8][9] Milan has won a joint record three Intercontinental Cups and one FIFA Club World Cup,[9] seven European Cup/Champions League titles (Italian record),[9] the UEFA Super Cup a joint record five times and the Cup Winners' Cup twice.[9] With 18 league titles, Milan is the third most successful club in Serie A, behind local rivals Inter Milan (19 league titles) and Juventus (36 league titles).[10] They have also won the Coppa Italia five times, and the Supercoppa Italiana seven.[9]Milan's home games",founded: "1899"),
            
        ])
    ]
    
    func togglePlayback(for item: Team) {
        
        for team in leagues.flatMap({ $0.teams })
        {
            if item.id == team.id {
                team.isPlaying.toggle()
            } else {
                team.isPlaying = false
            }
        }
        
    }
}
